# fly.toml file generated for solitary-pine-5604 on 2022-03-04T16:40:32-05:00

app = "solitary-pine-5604"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DOMAIN = "solitary-pine-5604.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
